# Generated by Django 4.2.2 on 2023-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watermarked_photo', models.UUIDField()),
                ('non_watermarked_photo', models.UUIDField()),
            ],
        ),
    ]
